name: Deploy Go web service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Go web service
        run: bash ./build.sh

      - name: Copy files to remote server
        run: scp -r -i ${{ secrets.SSH_KEY_BOOKS_VM }} ./webServicePOS ${{ secrets.HOST_USER }}@${{ secrets.HOST_IP }}:/go-web/ventabook

      - name: SSH into remote server and start service
        run: |
          ssh -i ${{ secrets.SSH_KEY_BOOKS_VM }} ${{ secrets.HOST_USER }}@${{ secrets.HOST_IP }} 'sudo service goweb stop'
          ssh -i ${{ secrets.SSH_KEY_BOOKS_VM }} ${{ secrets.HOST_USER }}@${{ secrets.HOST_IP }} 'sudo service goweb start'